Traceback (most recent call last):
  File "C:\Users\Trabalho\AppData\Local\pypoetry\Cache\virtualenvs\tp1-alg2-A0e5TZdT-py3.11\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Trabalho\AppData\Local\pypoetry\Cache\virtualenvs\tp1-alg2-A0e5TZdT-py3.11\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Trabalho\AppData\Local\pypoetry\Cache\virtualenvs\tp1-alg2-A0e5TZdT-py3.11\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\Trabalho\AppData\Local\pypoetry\Cache\virtualenvs\tp1-alg2-A0e5TZdT-py3.11\Lib\site-packages\nbclient\client.py", line 654, in async_setup_kernel
    yield
  File "C:\Users\Trabalho\AppData\Local\pypoetry\Cache\virtualenvs\tp1-alg2-A0e5TZdT-py3.11\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Trabalho\AppData\Local\pypoetry\Cache\virtualenvs\tp1-alg2-A0e5TZdT-py3.11\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Trabalho\AppData\Local\pypoetry\Cache\virtualenvs\tp1-alg2-A0e5TZdT-py3.11\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import time
import matplotlib.pyplot as plt

def files_name(folder):
    file_names = []
    for file_name in os.listdir(folder):
        full_path = os.path.join(folder, file_name)
        if os.path.isfile(full_path):
            file_names.append(file_name)
    return file_names



folder = 'agp2009a-simplerand'
file_names = files_name(folder)

t = []
num_v = []


for file in file_names:
    input = f"{folder}/{file}"
    poly = Polygon(input)
    t_i = time.time()
    result = triangulate(poly)
    t_f = time.time()
    t.append(t_f - t_i)
    num_v.append(len(poly.vertex_list))
print(len(num_v))
plt.scatter(num_v, t)

plt.title('RelaÃ§Ã£o entre Tempo e NÃºmero de VÃ©rtices')
plt.xlabel('NÃºmero de VÃ©rtices')
plt.ylabel('Tempo (s)')

plt.show()



------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[9], line 3[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mos[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mtime[39;00m
[1;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m      5[0m [38;5;28;01mdef[39;00m [38;5;21mfiles_name[39m(folder):
[0;32m      6[0m     file_names [38;5;241m=[39m []

[1;31mModuleNotFoundError[0m: No module named 'matplotlib'

